
spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 40000
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          auth0-login:
            client-id: ${essentialcloud-client-id}
            client-secret: ${essentialcloud-client-secret}
            provider: auth0
            scope: openid,profile
        provider:
          auth0:
            issuer-uri: ${essentialcloud-issuer-uri}

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

