
spring:
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          auth0-login:
            client-id: ${env.ESSENTIALCLOUD-CLIENT-ID}
            client-secret: ${env.ESSENTIALCLOUD-CLIENT-SECRET}
            provider: auth0
            scope: openid,profile
        provider:
          auth0:
            issuer-uri: ${env.ESSENTIALCLOUD-ISSUER-URI}

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

