spring:
  main:
    web-application-type: servlet
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: ${essentialcloud-issuer-uri}
      client:
        registration:
          auth0-login:
            client-id: ${essentialcloud-client-id}
            client-secret: ${essentialcloud-client-secret}
            authorization-grant-type: client_credentials
            provider: auth0
        provider:
          auth0:
            issuer-uri: ${essentialcloud-issuer-uri}

  jpa:
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8120
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#        http: DEBUG
